# Copyright 2025 Jiaqi Liu. All rights reserved.
---
name: CI/CD

"on":
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  NODE_VERSION: 22

jobs:
  documentation:
    name: Test & Release Documentation
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: true
      - name: Setup Node ${{ env.NODE_VERSION }}
        uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020 # v4.4.0
        with:
          node-version: ${{ env.NODE_VERSION }}
      - name: Install dependencies
        working-directory: docs
        run: npm install
      - name: Build documentation
        working-directory: docs
        run: npm run build
      - name: Deploy documentation (including Javadoc) to GitHub Pages
        uses: peaceiris/actions-gh-pages@4f9cc6602d3f66b9c108549d475ec49e8ef4d45e # v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: build
          enable_jekyll: false
          user_name: QubitPi
          user_email: jack20220723@gmail.com
          cname: component-testing.react.qubitpi.org
